name = "imperiawebv1-0"
compatibility_date = "2026-06-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "imperia-intake"
database_id = "360f714c-3eb0-44df-a931-2b35cd07b62f"
